# Generated by Django 5.2.7 on 2026-01-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('occupied', models.IntegerField()),
                ('available', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('full', 'Full')], max_length=10)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
