# Generated by Django 5.2.7 on 2026-01-22 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_monitor', '0002_add_missing_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('aller', 'Aller'), ('retour', 'Retour')], db_index=True, default='aller', help_text='Direction du trajet (aller ou retour)', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration_seconds', models.IntegerField(help_text='Durée du trajet en secondes (temps réel)')),
                ('duration_in_traffic_seconds', models.IntegerField(help_text='Durée du trajet avec trafic en secondes')),
                ('distance_meters', models.IntegerField(help_text='Distance en mètres')),
                ('traffic_status', models.CharField(choices=[('fluide', 'Fluide'), ('modere', 'Modéré'), ('embouteillage', 'Embouteillage'), ('bloque', 'Bloqué')], db_index=True, help_text='Statut du trafic', max_length=20)),
                ('delay_seconds', models.IntegerField(default=0, help_text='Délai dû au trafic en secondes')),
                ('delay_percentage', models.FloatField(default=0.0, help_text='Pourcentage de retard dû au trafic')),
                ('raw_data', models.JSONField(blank=True, help_text="Données brutes de l'API Google Maps", null=True)),
            ],
            options={
                'verbose_name': 'Traffic Status',
                'verbose_name_plural': 'Traffic Status',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='parkingstatus',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Parking Status'},
        ),
        migrations.AlterField(
            model_name='parkingstatus',
            name='available',
            field=models.IntegerField(default=20, help_text='Nombre de places disponibles (calculé)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parkingstatus',
            name='occupied',
            field=models.IntegerField(default=0, help_text='Nombre de places occupées', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parkingstatus',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('full', 'Complet')], db_index=True, default='available', help_text='Statut du parking', max_length=10),
        ),
        migrations.AlterField(
            model_name='parkingstatus',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='parkingstatus',
            name='total_spaces',
            field=models.IntegerField(default=20, help_text='Quota total de places', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddIndex(
            model_name='parkingstatus',
            index=models.Index(fields=['-timestamp'], name='parking_mon_timesta_6a700e_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingstatus',
            index=models.Index(fields=['status'], name='parking_mon_status_fcfc87_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingstatus',
            index=models.Index(fields=['source'], name='parking_mon_source_8cdc47_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficstatus',
            index=models.Index(fields=['-timestamp'], name='parking_mon_timesta_14f7b0_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficstatus',
            index=models.Index(fields=['traffic_status'], name='parking_mon_traffic_44e13d_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficstatus',
            index=models.Index(fields=['direction'], name='parking_mon_directi_09533a_idx'),
        ),
    ]
