# Generated by Django 5.2.7 on 2026-01-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_monitor', '0003_trafficstatus_alter_parkingstatus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_maps_enabled', models.BooleanField(default=True, help_text="Activer les requêtes vers l'API Google Maps")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres système',
                'verbose_name_plural': 'Paramètres système',
            },
        ),
    ]
